<?php
/**
 * Asset dependencies for BOG payment block
 * This file is auto-generated by WordPress build tools, but we're creating it manually
 */

return array(
    'dependencies' => array(
        'wc-blocks-registry',
        'wc-settings',
        'wp-element',
        'wp-html-entities',
        'wp-i18n',
    ),
    'version' => '1.0.0',
);